#!/bin/bash

echo "/home/zorthesosen/.config/qtile/themes/cyangenta/MDN-MDC-1312-v2.jpg" | tee /home/zorthesosen/.config/qtile/themes/current_theme_wallpaper
wal -c
wal -i /home/zorthesosen/.config/qtile/themes/cyangenta/MDN-MDC-1312-Theme-Cyangenta.jpg
screen -d -m feh --bg-fill /home/zorthesosen/.config/qtile/themes/cyangenta/MDN-MDC-1312-v2.jpg
