#!/bin/bash

echo "/home/zorthesosen/.config/qtile/themes/forest/MDN-MDC-1312-v2-Forest.jpg" | tee /home/zorthesosen/.config/qtile/themes/current_theme_wallpaper
wal -c
wal -i /home/zorthesosen/.config/qtile/themes/forest/MDN-MDC-1312-Theme-Forest.jpg
sleep 7
feh --bg-fill /home/zorthesosen/.config/qtile/themes/forest/MDN-MDC-1312-v2-Forest.jpg
