#!/bin/bash

wal -c
wal -i /home/zorthesosen/.config/qtile/themes/forest/MDN-MDC-1312-Theme-Forest.jpg
screen -d -m feh --bg-fill /home/zorthesosen/.config/qtile/themes/forest/MDN-MDC-1312-v2-Forest.jpg
